version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"

  discountdb:
    container_name: discountdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=DiscountDb
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  orderdb:
    container_name: orderdb
    environment:
      - MSSQL_SA_PASSWORD=Jmachin9112!
      - ACCEPT_EULA=Y
    restart: always
    ports:
        - "1450:1433"

  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=opennotice2015@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin

  portainer:
    container_name: portainer
    restart: always
    ports:
      - "8080:8000"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
    depends_on:
      - catalogdb
    ports:
      - "8000:80"

  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:redis=basketdb:6379"
      - "ConnectionStrings:discountURL=http://discount.grpc"
      - "ConnectionStrings:RabbitMQ=amqp://guest:guest@rabbitmq:5672"
    depends_on:
      - basketdb
      - rabbitmq
    ports:
      - "8001:80"

  discount.api:
    container_name: discount.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:postgres=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234;"
    depends_on:
      - discountdb
    ports:
      - "8002:80"

  discount.grpc:
    container_name: discount.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:postgres=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234;"
    depends_on:
      - discountdb
    ports:
      - "8003:80"

  ordering.api:
    container_name: ordering.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:sqlserver=Server=orderdb,1433;Database=OrderDb;User Id=sa;Password=Jmachin9112!;"
      - "ConnectionStrings:RabbitMQ=amqp://guest:guest@rabbitmq:5672"
      - "ConnectionStrings:IdentityServer=https://identity.server"
    depends_on:
      - orderdb
      - rabbitmq
      - identity.server
    ports:
      - "8004:80"

  # api gateways
  ocelot.apigw:
    container_name: ocelot.apigw
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - discount.api
      - ordering.api
      - basket.api
      - catalog.api
    ports:
      - "8010:80"

  shopping.aggregator:
    container_name: shopping.aggregator
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "APIEndpoints:Catalog=http://catalog.api"
      - "APIEndpoints:Basket=http://basket.api"
      - "APIEndpoints:Ordering=http://ordering.api"
    depends_on:
      - ordering.api
      - basket.api
      - catalog.api
    ports:
      - "8005:80"

  # broker
  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  identity.server:
    container_name: identity.server
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=asdasd!00
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
      - "8007:443"
      - "8008:80"
    volumes:
      - ~/.aspnet/https:/https:ro

  # webapps
  aspnetrunbasics:
    container_name: aspnetrunbasics
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ApiSettings:APIGW=http://ocelot.apigw"
    depends_on:
      - ocelot.apigw
      - catalog.api
      - basket.api
      - discount.api
      - ordering.api
    ports:
      - "8006:80"