version: '3.4'

services:
  catalogdb:
    image: mongo

  basketdb:
    image: redis

  portainer:
    image: portainer/portainer-ce

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: Services/Catalog/Catalog.API/
      dockerfile: Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: Services/Basket/Basket.API/
      dockerfile: Dockerfile

volumes:
  mongo_data: 
  portainer_data: