version: '3.4'

services:
# databases
  catalogdb:
    image: mongo

  basketdb:
    image: redis

  discountdb:
    image: postgres

# apis
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: Services/Catalog/Catalog.API/
      dockerfile: Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: Services/Basket/Basket.API/
      dockerfile: Dockerfile

  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: Services/Discount/Discount.API/
      dockerfile: Dockerfile

# utils
  pgadmin:
    image: dpage/pgadmin4

  portainer:
    image: portainer/portainer-ce

volumes:
  mongo_data: 
  portainer_data:
  postgres_data:
  pgadmin_data: