version: '3.4'

services:
# databases
  catalogdb:
    image: mongo

  basketdb:
    image: redis

  discountdb:
    image: postgres

  orderdb:
    image: mcr.microsoft.com/mssql/server

# apis
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: Services/Catalog/Catalog.API/
      dockerfile: Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: Services/Basket/Basket.API/
      dockerfile: Dockerfile

  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: Services/Discount/Discount.API/
      dockerfile: Dockerfile

  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: Services/Ordering/Ordering.API/
      dockerfile: Dockerfile

  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: Services/Discount/Discount.gRPC/
      dockerfile: Dockerfile

# utils
  pgadmin:
    image: dpage/pgadmin4

  portainer:
    image: portainer/portainer-ce

# broker
  rabbitmq:
    image: rabbitmq:management-alpine

# api gateways
  ocelot.apigw:
    image: ${DOCKER_REGISTRY-}ocelotapigw
    build:
      context: API.Gateways/Ocelot.APIGW/
      dockerfile: Dockerfile

  shopping.aggregator:
    image: ${DOCKER_REGISTRY-}shoppingaggregator
    build:
      context: API.Gateways/Shopping.Aggregator/
      dockerfile: Dockerfile

  identity.server:
    image: ${DOCKER_REGISTRY-}identityserver
    build:
      context: Identity/Identity.Server/
      dockerfile: Dockerfile

  aspnetrunbasics:
    image: ${DOCKER_REGISTRY-}aspnetrunbasics
    build:
      context: WebApps/AspnetRunBasics/
      dockerfile: Dockerfile

volumes:
  mongo_data: 
  portainer_data:
  postgres_data:
  pgadmin_data:
